export const SHIPPING_METHODS = [
	{
		id: "1",
		shipping_method: "Courier",
		description: "All addresses (default zone), United States & Canada",
		delivery_time: "2 - 4 days",
		fee: 26.5,
	},
	{
		id: "2",
		shipping_method: "Local Shipping",
		description: "All addresses (default zone), United States & Canada",
		delivery_time: "up to one week",
		fee: 10.0,
	},
	{
		id: "3",
		shipping_method: "Flat Rate",
		description: "All addresses (default zone)",
		delivery_time: "5 - 7 days",
		fee: 33.85,
	},
	{
		id: "4",
		shipping_method: "UPS Ground Shipping",
		description: "All addresses (default zone)",
		delivery_time: "4 - 6 days",
		fee: 18.0,
	},
	{
		id: "5",
		shipping_method: "Local Pickup from store",
		description: "All addresses (default zone)",
		delivery_time: "-",
		fee: 0.0,
	},
	{
		id: "6",
		shipping_method: "Pick Up at Cartzilla Locker",
		description: "All addresses (default zone), United States & Canada",
		delivery_time: "-",
		fee: 9.99,
	},
	{
		id: "7",
		shipping_method: "Cartzilla Global Export",
		description: "All addresses (default zone), United States & Canada",
		delivery_time: "3 - 4 days",
		fee: 25.0,
	},
	{
		id: "8",
		shipping_method: "Same-Day Delivery",
		description: "Only United States",
		delivery_time: "-",
		fee: 34.0,
	},
	{
		id: "9",
		shipping_method: "International Shipping",
		description: "All addresses (default zone)",
		delivery_time: "up to 15 days",
		fee: 27.0,
	},
];
