import { Product } from "~/types/product";

export const PRODUCTS: Product[] = [
	{
		category_name: "Light Green Comfort Inserts",
		name: "Stopping Sweating Feet",
		original_price: "$49.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/01.jpg",
		quantity: 1,
		href: "#",
		colors: ["#eaeaeb", "#d1dceb", "#f4e6a2", "#f3dcff"],
	},
	{
		category_name: "Inserts",
		name: "Moldable Orthotics for Adults",
		current_price: "$98.50",
		original_price: "$149.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/02.jpg",
		badge: "DME",
		badge_color: "error",
		quantity: 1,
		href: "#",
		sizes: ["6", "7", "8", "9"],
	},
	{
		category_name: "Ultimate Flying Shoes",
		name: "Monitoring Foot Motions",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/03.jpg",
		badge: "Used",
		badge_color: "info",
		quantity: 0,
		href: "#",
		colors: ["#eaeaeb", "#d1dceb", "#f4e6a2", "#f3dcff"],
		sizes: ["6", "7", "8", "9"],
	},
	{
		category_name: "Light Green Comfort Inserts",
		name: "Stopping Sweating Feet",
		original_price: "$49.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/04.jpg",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Shoes",
		name: "Athletic Footwear",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/05.jpg",
		badge: "Refurbished",
		badge_color: "primary",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Inserts",
		name: "Moldable Orthotics for Adults",
		current_price: "$98.50",
		original_price: "$149.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/06.jpg",
		badge: "DME",
		badge_color: "error",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Ultimate Flying Shoes",
		name: "Monitoring Foot Motions",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/07.jpg",
		badge: "Used",
		badge_color: "info",
		quantity: 0,
		href: "#",
	},
	{
		category_name: "Light Green Comfort Inserts",
		name: "Stopping Sweating Feet",
		original_price: "$49.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/08.jpg",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Shoes",
		name: "Athletic Footwear",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/09.jpg",
		badge: "Refurbished",
		badge_color: "primary",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Inserts",
		name: "Moldable Orthotics for Adults",
		current_price: "$98.50",
		original_price: "$149.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/10.jpg",
		badge: "DME",
		badge_color: "error",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Ultimate Flying Shoes",
		name: "Monitoring Foot Motions",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/11.jpg",
		badge: "Used",
		badge_color: "info",
		quantity: 0,
		href: "#",
	},
	{
		category_name: "Light Green Comfort Inserts",
		name: "Stopping Sweating Feet",
		original_price: "$49.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/12.jpg",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Shoes",
		name: "Athletic Footwear",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/13.jpg",
		badge: "Refurbished",
		badge_color: "primary",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Inserts",
		name: "Moldable Orthotics for Adults",
		current_price: "$98.50",
		original_price: "$149.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/14.jpg",
		badge: "DME",
		badge_color: "error",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Ultimate Flying Shoes",
		name: "Monitoring Foot Motions",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/15.jpg",
		badge: "Used",
		badge_color: "info",
		quantity: 0,
		href: "#",
	},
];

export const PRODUCT_GALLERY = [
	{
		image_url: "/images/shop/single/gallery/01.jpg",
		thumbnail_url: "/images/shop/single/gallery/th01.jpg",
	},
	{
		image_url: "/images/shop/single/gallery/02.jpg",
		thumbnail_url: "/images/shop/single/gallery/th02.jpg",
	},
	{
		image_url: "/images/shop/single/gallery/03.jpg",
		thumbnail_url: "/images/shop/single/gallery/th03.jpg",
	},
	{
		image_url: "/images/shop/single/gallery/04.jpg",
		thumbnail_url: "/images/shop/single/gallery/th04.jpg",
	},
];

export const SUGGESTED_PRODUCTS: Product[] = [
	{
		category_name: "Light Green Comfort Inserts",
		name: "Stopping Sweating Feet",
		original_price: "$49.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/01.jpg",
		quantity: 1,
		href: "#",
		colors: ["#eaeaeb", "#d1dceb", "#f4e6a2", "#f3dcff"],
	},
	{
		category_name: "Inserts",
		name: "Moldable Orthotics for Adults",
		current_price: "$98.50",
		original_price: "$149.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/02.jpg",
		badge: "DME",
		badge_color: "error",
		quantity: 1,
		href: "#",
		sizes: ["6", "7", "8", "9"],
	},
	{
		category_name: "Ultimate Flying Shoes",
		name: "Monitoring Foot Motions",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/03.jpg",
		badge: "Used",
		badge_color: "info",
		quantity: 0,
		href: "#",
		colors: ["#eaeaeb", "#d1dceb", "#f4e6a2", "#f3dcff"],
		sizes: ["6", "7", "8", "9"],
	},
	{
		category_name: "Light Green Comfort Inserts",
		name: "Stopping Sweating Feet",
		original_price: "$49.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/04.jpg",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Shoes",
		name: "Athletic Footwear",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/05.jpg",
		badge: "Refurbished",
		badge_color: "primary",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Inserts",
		name: "Moldable Orthotics for Adults",
		current_price: "$98.50",
		original_price: "$149.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/06.jpg",
		badge: "DME",
		badge_color: "error",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Ultimate Flying Shoes",
		name: "Monitoring Foot Motions",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/07.jpg",
		badge: "Used",
		badge_color: "info",
		quantity: 0,
		href: "#",
	},
	{
		category_name: "Light Green Comfort Inserts",
		name: "Stopping Sweating Feet",
		original_price: "$49.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/08.jpg",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Shoes",
		name: "Athletic Footwear",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/09.jpg",
		badge: "Refurbished",
		badge_color: "primary",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Inserts",
		name: "Moldable Orthotics for Adults",
		current_price: "$98.50",
		original_price: "$149.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/10.jpg",
		badge: "DME",
		badge_color: "error",
		quantity: 1,
		href: "#",
	},
	{
		category_name: "Ultimate Flying Shoes",
		name: "Monitoring Foot Motions",
		original_price: "$198.00",
		rating: 5,
		thumbnail_url: "/images/shop/catalog/11.jpg",
		badge: "Used",
		badge_color: "info",
		quantity: 0,
		href: "#",
	},
	{
		category_name: "Light Green Comfort Inserts",
		name: "Stopping Sweating Feet",
		original_price: "$49.99",
		rating: 4,
		thumbnail_url: "/images/shop/catalog/12.jpg",
		quantity: 1,
		href: "#",
	},
];
