import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { ChildrenType } from "~/@core/types";
import themeConfig from "~/configs/themeConfig";
import "./globals.css";

const rubik = Rubik({
	weight: ["400", "500", "600", "700"],
	display: "swap",
	preload: true,
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: {
		template: `%s | ${themeConfig.app_name}`,
		default: themeConfig.app_name,
	},
	description: "Generated by create next app",
};

type Props = ChildrenType;

const RootLayout = ({ children }: Props) => {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={rubik.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
